### ISSUE TITLE
Add IMU sensor

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/glider_hybrid_whoi#2]
Add Hector IMU plugin to hybrid and non-hybrid underwater glider models: http://wiki.ros.org/hector_gazebo_plugins

* Tune the configuration parameters to reflect the glider IMU (attitude and heading sensor performance supplied by WHOI

See the [uw_glider_itnerface.graphml](https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/blob/master/uw_glider_interface.graphml) for context.

**Comment by bsb808** [comment]
@WHOI Please provide the performance parameters for the IMU (attitude, compass, etc.)  onboard the gliders.  Best if you can specify the "XML Parameters" listed as part of the Hector ROS IMU Plugin: http://wiki.ros.org/hector_gazebo_plugins#GazeboRosImu

**Comment by rcamilli** [comment]
Current sensor is TCM3, performance is as follows:
Heading
Accuracy: 0.3 deg RMS
Precision: 0.1 deg RMS

Pitch
Accuracy: 0.2 deg RMS
Precision: 0.1 deg RMS

Roll
Accuracy: 0.2 deg RMS
Precision: 0.1 deg RMS

Accelerometer values are unused by the vehicle.  Vehicle flight computer calculates horizontal and vertical speed through water based on rate of ascent/descent and pitch angle.

**Comment by woensug-choi** [comment]
There had been an attempt to add a more complicated IMU sensor by Bruce. Which is not merged. Leaving as a note for later discussions.
https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/blob/2a7d0039f9de44825980669d1bc30775b9e5582a/glider_hybrid_whoi_description/urdf/uw_imu_plugin.xacro#L5-L53

**Comment by greg-burgess** [comment]
The TCM-3 IMU is the IMU used by the glider flight computer. The Backseat Driver (which computes navigation techniques of interest) will be using the "Sparton AHRS-M2" . This will allow for a direct serial connection from the BSD to the IMU. The Sparton AHRS-M2 has the following performance parameters:
https://www.spartonnavex.com/product/ahrs-m2/

updateRate (double): 10 Hz or 100 Hz


Dynamic Heading Accuracy | 1.0° RMS
-- | --
0.2° RMS (<1.0⁰ RMS from -40⁰ to +70⁰ C)
1.0° RMS
0.2° RMS
0.1° RMS
± 90°, ± 180°

**Comment by woensug-choi** [comment]
Made a PR https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/28 which add a hector IMU sensor.
I've set the update rate to 10 Hz. Performance parameters are not configured yet.

**Comment by woensug-choi** [comment]
PR https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/28 is merged.


Parameters
```
<updateRate>10</updateRate>
<gaussianNoise>0.00000001</gaussianNoise>
<xyzOffsets>0 0 0</xyzOffsets>
<rpyOffsets>0 0 0</rpyOffsets>
```

Topics
```
/glider_hybrid_whoi/hector_imu
/glider_hybrid_whoi/hector_imu/accel/parameter_descriptions
/glider_hybrid_whoi/hector_imu/accel/parameter_updates
/glider_hybrid_whoi/hector_imu/bias
/glider_hybrid_whoi/hector_imu/rate/parameter_descriptions
/glider_hybrid_whoi/hector_imu/rate/parameter_updates
/glider_hybrid_whoi/hector_imu/yaw/parameter_descriptions
/glider_hybrid_whoi/hector_imu/yaw/parameter_updates
```
Closing this issue page as it was for intial sensor set-up discussions. Please revive this issue page when we need further specifications or discussions.
