### ISSUE TITLE
Add DVL Sensor

### ISSUE THREAD

**Issue by crvogt** [Field-Robotics-Lab/glider_hybrid_whoi#24]
- Add DVL sensor to hybrid underwater glider
- Tune DVL parameters to reflect glider expected specifications

Basing sensor on [ds_sim DVL](https://bitbucket.org/whoidsl/ds_sim/src/master/)

`<scale>1 1 1</scale>` refers to the relative dimensions of the visual mesh. According to [this page](http://gazebosim.org/tutorials/?tut=attach_meshes), scale does not affect collision boxes.

`<updateRateHZ>7.0</updateRateHZ>` refers to the sensor and topic update rate. From what I can tell, the `<update_rate>` has no effect with the WHOI WHN model with no reference in `dsros_dvl_plugin.cc` and commenting it out has no apparent effect on the model operation.

**Comment by woensug-choi** [comment]
Error occured with dave dvl sensor.  https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/issues/47

**Comment by woensug-choi** [comment]
PR made for the DVL sensor PR https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/25. 
Current sensor specifications,
https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/blob/c840db6946c2a839a5153595d2aef2d300ad64b0/models/whoi_teledyne_whn/model.sdf#L20-L49
```XML
      <sensor name="dvl_sensor" type="dsros_dvl">
        <always_on>1</always_on>
        <update_rate>7.0</update_rate>
        <plugin name="dvl_sensor_controller" filename="libdsros_ros_dvl.so">
          <robotNamespace>dvl</robotNamespace>
          <topicName>dvl</topicName>
          <rangesTopicName>ranges</rangesTopicName>
          <frameName>dvl_base_link</frameName>
          <pointcloudFrame>dvl_base_link</pointcloudFrame>
          <updateRateHZ>7.0</updateRateHZ>
          <gaussianNoiseBeamVel>0.005</gaussianNoiseBeamVel>
          <gaussianNoiseBeamWtrVel>0.0075</gaussianNoiseBeamWtrVel>
          <gaussianNoiseBeamRange>0.1</gaussianNoiseBeamRange>
          <minRange>0.7</minRange>
          <maxRange>90.0</maxRange>
          <maxRangeDiff>10</maxRangeDiff>
          <beamAngleDeg>30.0</beamAngleDeg>
          <beamWidthDeg>4.0</beamWidthDeg>
          <beamAzimuthDeg1>-135</beamAzimuthDeg1>
          <beamAzimuthDeg2>135</beamAzimuthDeg2>
          <beamAzimuthDeg3>45</beamAzimuthDeg3>
          <beamAzimuthDeg4>-45</beamAzimuthDeg4>
          <enableWaterTrack>1</enableWaterTrack>
          <waterTrackBins>10</waterTrackBins>
          <currentProfileCoordMode>0</currentProfileCoordMode>
          <pos_z_down>false</pos_z_down>
          <collide_bitmask>0x0001</collide_bitmask>
        </plugin>
        <pose>0 0 0 0 0 0</pose>
      </sensor>
```

**Comment by woensug-choi** [comment]
PR https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/25 is merged.

Closing this issue page as it was for initial sensor set-up discussions. Please revive this issue page when we need further specifications or discussions.
