### ISSUE TITLE
Add depth sensor

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/glider_hybrid_whoi#4]
Need to simulate a glider depth sensor.

* What currently exists?
    * The UUV Simulator has a pressure sensor plugin.  Is this useful?  Is there documentation?  https://github.com/uuvsimulator/uuv_simulator/blob/master/uuv_sensor_plugins/uuv_sensor_ros_plugins/include/uuv_sensor_ros_plugins/SubseaPressureROSPlugin.hh
* If necessary, a simple plugin shouldn't be a big effort.
    * Should it use the WHOI Deep Submergence DepthPressure message?  This doesn't introduce a new dependency and provides some commonality.  https://bitbucket.org/whoidsl/ds_msgs/src/master/ds_sensor_msgs/msg/DepthPressure.msg

**Comment by bsb808** [comment]
@WHOI Please provide performance specification for the u/w glider depth sensor, e.g., precision and accuracy expressed as variance or stdev, range min/max., etc.

**Comment by greg-burgess** [comment]
Any pressure sensor that provides depth will suffice. 
Range: 
minimum- 0
maximum- 1362 meters

Accuracy:
+/- 1m

Precision: 
+/- .01m

**Comment by greg-burgess** [comment]
The SubseaPressureROSPlugin.cc will work fine

**Comment by woensug-choi** [comment]
PR https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/27 is made for the depth/pressure sensor.

**Comment by woensug-choi** [comment]
PR https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/27 is merged.

The pressure sensor can are defined as
```
      topic="pressure"
      mass="0.015"
      update_rate="10"
      range="1362"
      noise_sigma="3.0"
      noise_amplitude="0.0"
      estimateDepth="true"
      standardPressure="101.325"
      kPaPerM="9.80638">
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      <origin xyz="0.0 0.0 -0.0825" rpy="0 ${0.5*pi} 0" />
```

Closing this issue page as it was for intial sensor set-up discussions. Please revive this issue page when we need further specifications or discussions.
