### ISSUE TITLE
Absolute path to databasefilePath in world file unsustainable

### ISSUE THREAD

**Issue by daewok** [Field-Robotics-Lab/glider_hybrid_whoi#40]
It's not very user or developer friendly to require this repo be installed in a specific place to use it. Especially when that absolute path is under `/home` since it mandates a user name...

Could we pass the world files through xacro to use `$(find ...)`? Or maybe another approach?

**Comment by woensug-choi** [comment]
Both transient current and tidal oscillation database csv file can be defined in relative path and absolute path.
Currently, the relative path method written as below direct to the directory of the dave repo. 
https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/blob/a3d1139ce59214cb573f3bbd6c860daec895750d/glider_hybrid_whoi_gazebo/worlds/seafloor_underwater_stratified_current.world#L122
https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/blob/a3d1139ce59214cb573f3bbd6c860daec895750d/glider_hybrid_whoi_gazebo/worlds/seafloor_underwater_stratified_current.world#L133

So it's pretty much a relative path already considering that the glider repo will be merged to dave repo sometime after reorganizations happening at the dave repo.

**Comment by woensug-choi** [comment]
https://github.com/Field-Robotics-Lab/dave/pull/190

This shall fix it.

**Comment by woensug-choi** [comment]
https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/66 includes the solution.
