### ISSUE TITLE
Publish Docker image

### ISSUE THREAD

**Issue by daewok** [Field-Robotics-Lab/glider_hybrid_whoi#46]
It would be nice to publish a Docker image of the simulator somewhere so that
people can just download it instead of going through a lengthy build process.

**Comment by woensug-choi** [comment]
I can upload a docker image to the docker hub. I've done so with dave CI check workflow on Github. I can do that for every milestone version. We could achieve one soon!

**Comment by woensug-choi** [comment]
Luckly, there is an automated build settings between the Docker Hub and Github. I've managed to set-up an automated image build for the master branch. 
https://hub.docker.com/repository/docker/woensugchoi/glider_hybrid_whoi

**Comment by woensug-choi** [comment]
https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/52
