### ISSUE TITLE
Add altitude sensor

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/glider_hybrid_whoi#5]
Need to simulate a glider altitude sensor.

* What currently exists?
    * Couldn't find anything in UUV Simulator - but would be worth looking at.
* If necessary, a simple plugin shouldn't be a big effort.
    * Is there a standard altitude sensor measurement or do we need a new one?

To start with, we can use the model state to infer altitude.  Assume a flat bottom for now and that the seafloor is at the location of the seafloor heightmap model location.  Can assume altitude is measured directly below glider, despite the fact that the altimeter often is based on a slant range to the bottom - we can address that detail in a future pass.

**Comment by bsb808** [comment]
@WHOI  Please provide performance parameters for glider altitude measurements, e.g., precision and accuracy as stdev/var, min/max range, etc.

**Comment by greg-burgess** [comment]
The altimeter used onboard is the AIRMAR 200m Mini Altimeter Kit

On the vehicle, the altimeter is pitched 26 degrees above horizontal (if the glider is descending at a 26 degree angle, the altimeter is pointed straight down)

Update Rate is 4 seconds
Actual range is 2m - 100m

Accuracy Table
Actual | Reported | Difference | %
-- | -- | -- | --
3.05 m | 3.07 m | +0.02 m | 99.33%
4.57 m | 4.59 m | +0.02 m | 99.56%
5.79 m | 5.82 m | +0.03 m | 99.48%

Specifications (range, accuracy table, etc.) can be found here:
https://www.airmar.com/productdescription.html?id=221

**Comment by woensug-choi** [comment]
Do we need this sensor although altitude is being obtained by DVL sensor?
The DVL sensor developed at the Dave project, which is now included in this repository (PR https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/25), can represent Teledyne WHN. The previous DVL sensor developed before the Dave project has a simpler specification set-up. If we need a separate altimeter sensor, which does not exist, I could add a simpler previous DVL sensor and name it as an altimeter. 

PR https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/26 is made with a simpler previous DVL sensor with the orientation and refresh rate we need.

**Comment by woensug-choi** [comment]
https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/pull/26 is merged.
An altimeter is added with a pre-Dave project (UUV simulator's) DVL sensor. The DVL sensor has simpler specifications available than the Dave project's one. It has some link names with the phrase dvl but added to act as an altimeter with the orientation we need.

#### Specifications
- The altimeter is pitched 26 degrees above horizontal (if the glider is descending at a 26 degree angle, the altimeter is pointed straight down)
- Update Rate is 4 seconds (0.25 Hz)

#### Topic lists
`/glider_hybrid_whoi/altimeter`
`/glider_hybrid_whoi/altimeter/state`
`/glider_hybrid_whoi/altimeter_sonar0`
`/glider_hybrid_whoi/altimeter_sonar1`
`/glider_hybrid_whoi/altimeter_sonar2`
`/glider_hybrid_whoi/altimeter_sonar3`
`/glider_hybrid_whoi/altimeter_twist`

Closing this issue page as it was for initial sensor set-up discussions. Please revive this issue page when we need further specifications or discussions.
